# Generated by Django 6.0.2 on 2026-03-02 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(choices=[('BLOCKED', 'Bloqueado'), ('AVAILABLE', 'Disponible extra')], default='BLOCKED', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['day_number', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='day_number',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'day_number', 'start_time'), name='unique_schedule_slot'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'start_time'), name='unique_exception_slot'),
        ),
    ]
