# Generated by Django 6.0.2 on 2026-03-02 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_scheduleexception_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('specialty', models.CharField(choices=[('GENERAL', 'Medicina General'), ('PEDIATRICS', 'Pediatría'), ('CARDIOLOGY', 'Cardiología'), ('DERMATOLOGY', 'Dermatología'), ('GYNECOLOGY', 'Ginecología'), ('NEUROLOGY', 'Neurología'), ('ORTHOPEDICS', 'Ortopedia'), ('PSYCHIATRY', 'Psiquiatría'), ('OPHTHALMOLOGY', 'Oftalmología'), ('OTOLARYNGOLOGY', 'Otorrinolaringología'), ('UROLOGY', 'Urología'), ('ENDOCRINOLOGY', 'Endocrinología'), ('OTHER', 'Otra')], default='GENERAL', max_length=30)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
