# Generated by Django 5.2 on 2026-04-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(choices=[('GENERAL', 'General Medicine'), ('PEDIATRICS', 'Pediatrics'), ('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('GYNECOLOGY', 'Gynecology'), ('NEUROLOGY', 'Neurology'), ('ORTHOPEDICS', 'Orthopedics'), ('PSYCHIATRY', 'Psychiatry'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('OTOLARYNGOLOGY', 'Otolaryngology'), ('UROLOGY', 'Urology'), ('ENDOCRINOLOGY', 'Endocrinology'), ('OTHER', 'Other')], default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='type',
            field=models.CharField(choices=[('BLOCKED', 'Blocked'), ('AVAILABLE', 'Extra Availability')], default='BLOCKED', max_length=20),
        ),
    ]
