# Generated by Django 6.0.2 on 2026-03-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='estado',
        ),
    ]
