# Generated by Django 5.2 on 2026-04-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='busqueda.doctor'),
        ),
    ]
