# Generated by Django 6.0.5 on 2026-05-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0002_remove_disponibilidad_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
